### ISSUE TITLE
Can't get two icons working with darkMode

### ISSUE THREAD

**Issue by TheManFromEarth1** [TheManFromEarth1/hkt-icons#10]
I was able to add new icons, but these two I couldn't figure out yet.

Home.svg (without CurrentColor)
`<path d="m16 9.414-4.5-4.5L4.414 12H6v8h11v-8h1.586L17 10.414l-1-1zM2 13l9.5-9.5L15 7l3 3 3 3h-3v7.998h-5V21l-3-.002H5V13H2z"/>`

Favorite.svg (with CurrentColor)
`<path fill="currentColor" d="M4.244 12.252A4.25 4.25 0 1 1 10.94 7.14h1.117a4.25 4.25 0 1 1 6.698 5.11l-7.257 7.259-7.255-7.257v-.001Zm15.218.71a5.25 5.25 0 1 0-7.963-6.795 5.25 5.25 0 1 0-7.961 6.795l7.962 7.96 7.962-7.96Z"/>`

![image](https://user-images.githubusercontent.com/57072774/188507834-77e8ab93-cc79-4be6-9aa4-b1dbdef00117.png)

**Comment by TheManFromEarth1** [comment]
Workaround: 
Add Tailwind class when using Icon inside project.
<Home class="dark:text-white" />

**Comment by TiagoCavalcante** [comment]
The icon is correct, different classes were applied to the sidebar icons because of the parent element.
